name: mckibz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1853
title: MC Kibz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161614'
    - '#d8c1a2'
    - '#9b5c3b'
    - '#5b5c4c'
    - '#b98570'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
