name: mckibz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0624805698171258
title: MC Kibz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#86451f'
    - '#f7fcf6'
    - '#000000'
    - '#787167'
    - '#cfcbc8'
  brandStrength: 0.5625
  lightness: 0.9601155777927488
  saturation: 0.31396450637839735
  rhythmicContrast: 0.06847674283199012
purpose: []
